import { DatePicker, Form, Input, Table, Typography } from "antd";
import { ColumnsType } from "antd/lib/table";
import Head from "next/head";

export default function Home() {
  interface IOrders {
    Order_name: string;
    Product: string;
    Company_name: string;
    Name: string;
    Created_at: string;
    Total_amount: number;
    Delivered_amount: number;
  }

  const data = [
    {
      Order_name: "PO #001-I",
      Product: "Corrugated Box",
      Company_name: "Roga & Kopyta",
      Name: "Ivan Ivanovich",
      Created_at: "2020-01-02T00:00:00Z",
      Total_amount: 13.454,
      Delivered_amount: 6.727,
    },
  ];

  const [form] = Form.useForm();
  const columns: ColumnsType<IOrders> = [
    {
      title: "Order name",
      dataIndex: "Order_name",
      key: "Order_name",
      render: (text) => <Typography.Paragraph>{text}</Typography.Paragraph>,
    },
  ];
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Form form={form}>
        <div>
          <Typography.Title>Search</Typography.Title>
          <Input size="large" />
        </div>
        <div>
          <Typography.Paragraph>Created Date</Typography.Paragraph>
          <DatePicker.RangePicker />
        </div>
        <div>
          <Typography.Paragraph>Total Amount</Typography.Paragraph>
        </div>
        <Table columns={columns} dataSource={data} />
      </Form>
    </div>
  );
}
